// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: several_to_one.proto
#ifndef GRPC_several_5fto_5fone_2eproto__INCLUDED
#define GRPC_several_5fto_5fone_2eproto__INCLUDED

#include "several_to_one.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace sto {

class several_to_one final {
 public:
  static constexpr char const* service_full_name() {
    return "sto.several_to_one";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetCount0(::grpc::ClientContext* context, const ::sto::AddCount0Request& request, ::sto::ValueOfCount0* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sto::ValueOfCount0>> AsyncGetCount0(::grpc::ClientContext* context, const ::sto::AddCount0Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sto::ValueOfCount0>>(AsyncGetCount0Raw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sto::ValueOfCount0>> PrepareAsyncGetCount0(::grpc::ClientContext* context, const ::sto::AddCount0Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sto::ValueOfCount0>>(PrepareAsyncGetCount0Raw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetCount0(::grpc::ClientContext* context, const ::sto::AddCount0Request* request, ::sto::ValueOfCount0* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetCount0(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sto::ValueOfCount0* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sto::ValueOfCount0>* AsyncGetCount0Raw(::grpc::ClientContext* context, const ::sto::AddCount0Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sto::ValueOfCount0>* PrepareAsyncGetCount0Raw(::grpc::ClientContext* context, const ::sto::AddCount0Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetCount0(::grpc::ClientContext* context, const ::sto::AddCount0Request& request, ::sto::ValueOfCount0* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sto::ValueOfCount0>> AsyncGetCount0(::grpc::ClientContext* context, const ::sto::AddCount0Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sto::ValueOfCount0>>(AsyncGetCount0Raw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sto::ValueOfCount0>> PrepareAsyncGetCount0(::grpc::ClientContext* context, const ::sto::AddCount0Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sto::ValueOfCount0>>(PrepareAsyncGetCount0Raw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetCount0(::grpc::ClientContext* context, const ::sto::AddCount0Request* request, ::sto::ValueOfCount0* response, std::function<void(::grpc::Status)>) override;
      void GetCount0(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sto::ValueOfCount0* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::sto::ValueOfCount0>* AsyncGetCount0Raw(::grpc::ClientContext* context, const ::sto::AddCount0Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sto::ValueOfCount0>* PrepareAsyncGetCount0Raw(::grpc::ClientContext* context, const ::sto::AddCount0Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetCount0_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetCount0(::grpc::ServerContext* context, const ::sto::AddCount0Request* request, ::sto::ValueOfCount0* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetCount0 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetCount0() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetCount0() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCount0(::grpc::ServerContext* context, const ::sto::AddCount0Request* request, ::sto::ValueOfCount0* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCount0(::grpc::ServerContext* context, ::sto::AddCount0Request* request, ::grpc::ServerAsyncResponseWriter< ::sto::ValueOfCount0>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetCount0<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetCount0 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_GetCount0() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::sto::AddCount0Request, ::sto::ValueOfCount0>(
          [this](::grpc::ServerContext* context,
                 const ::sto::AddCount0Request* request,
                 ::sto::ValueOfCount0* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->GetCount0(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_GetCount0() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCount0(::grpc::ServerContext* context, const ::sto::AddCount0Request* request, ::sto::ValueOfCount0* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void GetCount0(::grpc::ServerContext* context, const ::sto::AddCount0Request* request, ::sto::ValueOfCount0* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_GetCount0<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetCount0 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetCount0() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetCount0() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCount0(::grpc::ServerContext* context, const ::sto::AddCount0Request* request, ::sto::ValueOfCount0* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetCount0 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_GetCount0() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetCount0() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCount0(::grpc::ServerContext* context, const ::sto::AddCount0Request* request, ::sto::ValueOfCount0* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCount0(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetCount0 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_GetCount0() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->GetCount0(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_GetCount0() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCount0(::grpc::ServerContext* context, const ::sto::AddCount0Request* request, ::sto::ValueOfCount0* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void GetCount0(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetCount0 : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetCount0() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::sto::AddCount0Request, ::sto::ValueOfCount0>(std::bind(&WithStreamedUnaryMethod_GetCount0<BaseClass>::StreamedGetCount0, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetCount0() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetCount0(::grpc::ServerContext* context, const ::sto::AddCount0Request* request, ::sto::ValueOfCount0* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetCount0(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sto::AddCount0Request,::sto::ValueOfCount0>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetCount0<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetCount0<Service > StreamedService;
};

}  // namespace sto


#endif  // GRPC_several_5fto_5fone_2eproto__INCLUDED
