// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: several_to_one.proto

#include "several_to_one.pb.h"
#include "several_to_one.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace sto {

static const char* several_to_one_method_names[] = {
  "/sto.several_to_one/GetCount0",
};

std::unique_ptr< several_to_one::Stub> several_to_one::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< several_to_one::Stub> stub(new several_to_one::Stub(channel));
  return stub;
}

several_to_one::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetCount0_(several_to_one_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status several_to_one::Stub::GetCount0(::grpc::ClientContext* context, const ::sto::AddCount0Request& request, ::sto::ValueOfCount0* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetCount0_, context, request, response);
}

void several_to_one::Stub::experimental_async::GetCount0(::grpc::ClientContext* context, const ::sto::AddCount0Request* request, ::sto::ValueOfCount0* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetCount0_, context, request, response, std::move(f));
}

void several_to_one::Stub::experimental_async::GetCount0(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sto::ValueOfCount0* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetCount0_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::sto::ValueOfCount0>* several_to_one::Stub::AsyncGetCount0Raw(::grpc::ClientContext* context, const ::sto::AddCount0Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::sto::ValueOfCount0>::Create(channel_.get(), cq, rpcmethod_GetCount0_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::sto::ValueOfCount0>* several_to_one::Stub::PrepareAsyncGetCount0Raw(::grpc::ClientContext* context, const ::sto::AddCount0Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::sto::ValueOfCount0>::Create(channel_.get(), cq, rpcmethod_GetCount0_, context, request, false);
}

several_to_one::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      several_to_one_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< several_to_one::Service, ::sto::AddCount0Request, ::sto::ValueOfCount0>(
          std::mem_fn(&several_to_one::Service::GetCount0), this)));
}

several_to_one::Service::~Service() {
}

::grpc::Status several_to_one::Service::GetCount0(::grpc::ServerContext* context, const ::sto::AddCount0Request* request, ::sto::ValueOfCount0* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sto

