// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: several_to_one.proto

#include "several_to_one.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace sto {
class AddCount0RequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<AddCount0Request> _instance;
} _AddCount0Request_default_instance_;
class ValueOfCount0DefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ValueOfCount0> _instance;
} _ValueOfCount0_default_instance_;
}  // namespace sto
static void InitDefaultsAddCount0Request_several_5fto_5fone_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sto::_AddCount0Request_default_instance_;
    new (ptr) ::sto::AddCount0Request();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sto::AddCount0Request::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_AddCount0Request_several_5fto_5fone_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsAddCount0Request_several_5fto_5fone_2eproto}, {}};

static void InitDefaultsValueOfCount0_several_5fto_5fone_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::sto::_ValueOfCount0_default_instance_;
    new (ptr) ::sto::ValueOfCount0();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::sto::ValueOfCount0::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ValueOfCount0_several_5fto_5fone_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsValueOfCount0_several_5fto_5fone_2eproto}, {}};

void InitDefaults_several_5fto_5fone_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_AddCount0Request_several_5fto_5fone_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ValueOfCount0_several_5fto_5fone_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_several_5fto_5fone_2eproto[2];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_several_5fto_5fone_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_several_5fto_5fone_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_several_5fto_5fone_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sto::AddCount0Request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::sto::AddCount0Request, index_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::sto::ValueOfCount0, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::sto::ValueOfCount0, value0_),
  PROTOBUF_FIELD_OFFSET(::sto::ValueOfCount0, value1_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::sto::AddCount0Request)},
  { 6, -1, sizeof(::sto::ValueOfCount0)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::sto::_AddCount0Request_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::sto::_ValueOfCount0_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_several_5fto_5fone_2eproto = {
  {}, AddDescriptors_several_5fto_5fone_2eproto, "several_to_one.proto", schemas,
  file_default_instances, TableStruct_several_5fto_5fone_2eproto::offsets,
  file_level_metadata_several_5fto_5fone_2eproto, 2, file_level_enum_descriptors_several_5fto_5fone_2eproto, file_level_service_descriptors_several_5fto_5fone_2eproto,
};

const char descriptor_table_protodef_several_5fto_5fone_2eproto[] =
  "\n\024several_to_one.proto\022\003sto\"!\n\020AddCount0"
  "Request\022\r\n\005index\030\001 \001(\005\"/\n\rValueOfCount0\022"
  "\016\n\006value0\030\001 \001(\005\022\016\n\006value1\030\002 \001(\0052H\n\016sever"
  "al_to_one\0226\n\tGetCount0\022\025.sto.AddCount0Re"
  "quest\032\022.sto.ValueOfCount0b\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_several_5fto_5fone_2eproto = {
  false, InitDefaults_several_5fto_5fone_2eproto, 
  descriptor_table_protodef_several_5fto_5fone_2eproto,
  "several_to_one.proto", &assign_descriptors_table_several_5fto_5fone_2eproto, 193,
};

void AddDescriptors_several_5fto_5fone_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_several_5fto_5fone_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_several_5fto_5fone_2eproto = []() { AddDescriptors_several_5fto_5fone_2eproto(); return true; }();
namespace sto {

// ===================================================================

void AddCount0Request::InitAsDefaultInstance() {
}
class AddCount0Request::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int AddCount0Request::kIndexFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

AddCount0Request::AddCount0Request()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sto.AddCount0Request)
}
AddCount0Request::AddCount0Request(const AddCount0Request& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  index_ = from.index_;
  // @@protoc_insertion_point(copy_constructor:sto.AddCount0Request)
}

void AddCount0Request::SharedCtor() {
  index_ = 0;
}

AddCount0Request::~AddCount0Request() {
  // @@protoc_insertion_point(destructor:sto.AddCount0Request)
  SharedDtor();
}

void AddCount0Request::SharedDtor() {
}

void AddCount0Request::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const AddCount0Request& AddCount0Request::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_AddCount0Request_several_5fto_5fone_2eproto.base);
  return *internal_default_instance();
}


void AddCount0Request::Clear() {
// @@protoc_insertion_point(message_clear_start:sto.AddCount0Request)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  index_ = 0;
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* AddCount0Request::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<AddCount0Request*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int32 index = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_index(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool AddCount0Request::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sto.AddCount0Request)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 index = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &index_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sto.AddCount0Request)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sto.AddCount0Request)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void AddCount0Request::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sto.AddCount0Request)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 index = 1;
  if (this->index() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->index(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sto.AddCount0Request)
}

::google::protobuf::uint8* AddCount0Request::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sto.AddCount0Request)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 index = 1;
  if (this->index() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->index(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sto.AddCount0Request)
  return target;
}

size_t AddCount0Request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sto.AddCount0Request)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 index = 1;
  if (this->index() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->index());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void AddCount0Request::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sto.AddCount0Request)
  GOOGLE_DCHECK_NE(&from, this);
  const AddCount0Request* source =
      ::google::protobuf::DynamicCastToGenerated<AddCount0Request>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sto.AddCount0Request)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sto.AddCount0Request)
    MergeFrom(*source);
  }
}

void AddCount0Request::MergeFrom(const AddCount0Request& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sto.AddCount0Request)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.index() != 0) {
    set_index(from.index());
  }
}

void AddCount0Request::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sto.AddCount0Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AddCount0Request::CopyFrom(const AddCount0Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sto.AddCount0Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool AddCount0Request::IsInitialized() const {
  return true;
}

void AddCount0Request::Swap(AddCount0Request* other) {
  if (other == this) return;
  InternalSwap(other);
}
void AddCount0Request::InternalSwap(AddCount0Request* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(index_, other->index_);
}

::google::protobuf::Metadata AddCount0Request::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_several_5fto_5fone_2eproto);
  return ::file_level_metadata_several_5fto_5fone_2eproto[kIndexInFileMessages];
}


// ===================================================================

void ValueOfCount0::InitAsDefaultInstance() {
}
class ValueOfCount0::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ValueOfCount0::kValue0FieldNumber;
const int ValueOfCount0::kValue1FieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ValueOfCount0::ValueOfCount0()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:sto.ValueOfCount0)
}
ValueOfCount0::ValueOfCount0(const ValueOfCount0& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&value0_, &from.value0_,
    static_cast<size_t>(reinterpret_cast<char*>(&value1_) -
    reinterpret_cast<char*>(&value0_)) + sizeof(value1_));
  // @@protoc_insertion_point(copy_constructor:sto.ValueOfCount0)
}

void ValueOfCount0::SharedCtor() {
  ::memset(&value0_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value1_) -
      reinterpret_cast<char*>(&value0_)) + sizeof(value1_));
}

ValueOfCount0::~ValueOfCount0() {
  // @@protoc_insertion_point(destructor:sto.ValueOfCount0)
  SharedDtor();
}

void ValueOfCount0::SharedDtor() {
}

void ValueOfCount0::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ValueOfCount0& ValueOfCount0::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ValueOfCount0_several_5fto_5fone_2eproto.base);
  return *internal_default_instance();
}


void ValueOfCount0::Clear() {
// @@protoc_insertion_point(message_clear_start:sto.ValueOfCount0)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&value0_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&value1_) -
      reinterpret_cast<char*>(&value0_)) + sizeof(value1_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ValueOfCount0::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ValueOfCount0*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // int32 value0 = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 8) goto handle_unusual;
        msg->set_value0(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // int32 value1 = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        msg->set_value1(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ValueOfCount0::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:sto.ValueOfCount0)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 value0 = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (8 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &value0_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 value1 = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &value1_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:sto.ValueOfCount0)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:sto.ValueOfCount0)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ValueOfCount0::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:sto.ValueOfCount0)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 value0 = 1;
  if (this->value0() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->value0(), output);
  }

  // int32 value1 = 2;
  if (this->value1() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->value1(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:sto.ValueOfCount0)
}

::google::protobuf::uint8* ValueOfCount0::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:sto.ValueOfCount0)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 value0 = 1;
  if (this->value0() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->value0(), target);
  }

  // int32 value1 = 2;
  if (this->value1() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->value1(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:sto.ValueOfCount0)
  return target;
}

size_t ValueOfCount0::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:sto.ValueOfCount0)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // int32 value0 = 1;
  if (this->value0() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->value0());
  }

  // int32 value1 = 2;
  if (this->value1() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->value1());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ValueOfCount0::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:sto.ValueOfCount0)
  GOOGLE_DCHECK_NE(&from, this);
  const ValueOfCount0* source =
      ::google::protobuf::DynamicCastToGenerated<ValueOfCount0>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:sto.ValueOfCount0)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:sto.ValueOfCount0)
    MergeFrom(*source);
  }
}

void ValueOfCount0::MergeFrom(const ValueOfCount0& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:sto.ValueOfCount0)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.value0() != 0) {
    set_value0(from.value0());
  }
  if (from.value1() != 0) {
    set_value1(from.value1());
  }
}

void ValueOfCount0::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:sto.ValueOfCount0)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ValueOfCount0::CopyFrom(const ValueOfCount0& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:sto.ValueOfCount0)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ValueOfCount0::IsInitialized() const {
  return true;
}

void ValueOfCount0::Swap(ValueOfCount0* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ValueOfCount0::InternalSwap(ValueOfCount0* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(value0_, other->value0_);
  swap(value1_, other->value1_);
}

::google::protobuf::Metadata ValueOfCount0::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_several_5fto_5fone_2eproto);
  return ::file_level_metadata_several_5fto_5fone_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace sto
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::sto::AddCount0Request* Arena::CreateMaybeMessage< ::sto::AddCount0Request >(Arena* arena) {
  return Arena::CreateInternal< ::sto::AddCount0Request >(arena);
}
template<> PROTOBUF_NOINLINE ::sto::ValueOfCount0* Arena::CreateMaybeMessage< ::sto::ValueOfCount0 >(Arena* arena) {
  return Arena::CreateInternal< ::sto::ValueOfCount0 >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
