// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: SeveralToSeveral.proto
#ifndef GRPC_SeveralToSeveral_2eproto__INCLUDED
#define GRPC_SeveralToSeveral_2eproto__INCLUDED

#include "SeveralToSeveral.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace sts {

class SeveralToSeveral final {
 public:
  static constexpr char const* service_full_name() {
    return "sts.SeveralToSeveral";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetCnt(::grpc::ClientContext* context, const ::sts::AddCntRequest& request, ::sts::ValueOfCnt* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sts::ValueOfCnt>> AsyncGetCnt(::grpc::ClientContext* context, const ::sts::AddCntRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sts::ValueOfCnt>>(AsyncGetCntRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sts::ValueOfCnt>> PrepareAsyncGetCnt(::grpc::ClientContext* context, const ::sts::AddCntRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::sts::ValueOfCnt>>(PrepareAsyncGetCntRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetCnt(::grpc::ClientContext* context, const ::sts::AddCntRequest* request, ::sts::ValueOfCnt* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetCnt(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sts::ValueOfCnt* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sts::ValueOfCnt>* AsyncGetCntRaw(::grpc::ClientContext* context, const ::sts::AddCntRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::sts::ValueOfCnt>* PrepareAsyncGetCntRaw(::grpc::ClientContext* context, const ::sts::AddCntRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetCnt(::grpc::ClientContext* context, const ::sts::AddCntRequest& request, ::sts::ValueOfCnt* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sts::ValueOfCnt>> AsyncGetCnt(::grpc::ClientContext* context, const ::sts::AddCntRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sts::ValueOfCnt>>(AsyncGetCntRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sts::ValueOfCnt>> PrepareAsyncGetCnt(::grpc::ClientContext* context, const ::sts::AddCntRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::sts::ValueOfCnt>>(PrepareAsyncGetCntRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetCnt(::grpc::ClientContext* context, const ::sts::AddCntRequest* request, ::sts::ValueOfCnt* response, std::function<void(::grpc::Status)>) override;
      void GetCnt(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::sts::ValueOfCnt* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::sts::ValueOfCnt>* AsyncGetCntRaw(::grpc::ClientContext* context, const ::sts::AddCntRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::sts::ValueOfCnt>* PrepareAsyncGetCntRaw(::grpc::ClientContext* context, const ::sts::AddCntRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetCnt_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetCnt(::grpc::ServerContext* context, const ::sts::AddCntRequest* request, ::sts::ValueOfCnt* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetCnt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_GetCnt() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetCnt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCnt(::grpc::ServerContext* context, const ::sts::AddCntRequest* request, ::sts::ValueOfCnt* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCnt(::grpc::ServerContext* context, ::sts::AddCntRequest* request, ::grpc::ServerAsyncResponseWriter< ::sts::ValueOfCnt>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetCnt<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetCnt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_GetCnt() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::sts::AddCntRequest, ::sts::ValueOfCnt>(
          [this](::grpc::ServerContext* context,
                 const ::sts::AddCntRequest* request,
                 ::sts::ValueOfCnt* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->GetCnt(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_GetCnt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCnt(::grpc::ServerContext* context, const ::sts::AddCntRequest* request, ::sts::ValueOfCnt* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void GetCnt(::grpc::ServerContext* context, const ::sts::AddCntRequest* request, ::sts::ValueOfCnt* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_GetCnt<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetCnt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_GetCnt() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetCnt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCnt(::grpc::ServerContext* context, const ::sts::AddCntRequest* request, ::sts::ValueOfCnt* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetCnt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_GetCnt() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetCnt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCnt(::grpc::ServerContext* context, const ::sts::AddCntRequest* request, ::sts::ValueOfCnt* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetCnt(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetCnt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_GetCnt() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->GetCnt(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_GetCnt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetCnt(::grpc::ServerContext* context, const ::sts::AddCntRequest* request, ::sts::ValueOfCnt* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void GetCnt(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetCnt : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_GetCnt() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::sts::AddCntRequest, ::sts::ValueOfCnt>(std::bind(&WithStreamedUnaryMethod_GetCnt<BaseClass>::StreamedGetCnt, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_GetCnt() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetCnt(::grpc::ServerContext* context, const ::sts::AddCntRequest* request, ::sts::ValueOfCnt* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetCnt(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::sts::AddCntRequest,::sts::ValueOfCnt>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetCnt<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetCnt<Service > StreamedService;
};

}  // namespace sts


#endif  // GRPC_SeveralToSeveral_2eproto__INCLUDED
