// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SeveralToSeveral.proto

#ifndef PROTOBUF_INCLUDED_SeveralToSeveral_2eproto
#define PROTOBUF_INCLUDED_SeveralToSeveral_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_SeveralToSeveral_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_SeveralToSeveral_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_SeveralToSeveral_2eproto();
namespace sts {
class AddCntRequest;
class AddCntRequestDefaultTypeInternal;
extern AddCntRequestDefaultTypeInternal _AddCntRequest_default_instance_;
class ValueOfCnt;
class ValueOfCntDefaultTypeInternal;
extern ValueOfCntDefaultTypeInternal _ValueOfCnt_default_instance_;
}  // namespace sts
namespace google {
namespace protobuf {
template<> ::sts::AddCntRequest* Arena::CreateMaybeMessage<::sts::AddCntRequest>(Arena*);
template<> ::sts::ValueOfCnt* Arena::CreateMaybeMessage<::sts::ValueOfCnt>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace sts {

// ===================================================================

class AddCntRequest final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sts.AddCntRequest) */ {
 public:
  AddCntRequest();
  virtual ~AddCntRequest();

  AddCntRequest(const AddCntRequest& from);

  inline AddCntRequest& operator=(const AddCntRequest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  AddCntRequest(AddCntRequest&& from) noexcept
    : AddCntRequest() {
    *this = ::std::move(from);
  }

  inline AddCntRequest& operator=(AddCntRequest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const AddCntRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const AddCntRequest* internal_default_instance() {
    return reinterpret_cast<const AddCntRequest*>(
               &_AddCntRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(AddCntRequest* other);
  friend void swap(AddCntRequest& a, AddCntRequest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline AddCntRequest* New() const final {
    return CreateMaybeMessage<AddCntRequest>(nullptr);
  }

  AddCntRequest* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<AddCntRequest>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const AddCntRequest& from);
  void MergeFrom(const AddCntRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AddCntRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 index = 1;
  void clear_index();
  static const int kIndexFieldNumber = 1;
  ::google::protobuf::int32 index() const;
  void set_index(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:sts.AddCntRequest)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 index_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_SeveralToSeveral_2eproto;
};
// -------------------------------------------------------------------

class ValueOfCnt final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:sts.ValueOfCnt) */ {
 public:
  ValueOfCnt();
  virtual ~ValueOfCnt();

  ValueOfCnt(const ValueOfCnt& from);

  inline ValueOfCnt& operator=(const ValueOfCnt& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ValueOfCnt(ValueOfCnt&& from) noexcept
    : ValueOfCnt() {
    *this = ::std::move(from);
  }

  inline ValueOfCnt& operator=(ValueOfCnt&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const ValueOfCnt& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ValueOfCnt* internal_default_instance() {
    return reinterpret_cast<const ValueOfCnt*>(
               &_ValueOfCnt_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ValueOfCnt* other);
  friend void swap(ValueOfCnt& a, ValueOfCnt& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ValueOfCnt* New() const final {
    return CreateMaybeMessage<ValueOfCnt>(nullptr);
  }

  ValueOfCnt* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ValueOfCnt>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ValueOfCnt& from);
  void MergeFrom(const ValueOfCnt& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ValueOfCnt* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  ::google::protobuf::int32 value() const;
  void set_value(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:sts.ValueOfCnt)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 value_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_SeveralToSeveral_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// AddCntRequest

// int32 index = 1;
inline void AddCntRequest::clear_index() {
  index_ = 0;
}
inline ::google::protobuf::int32 AddCntRequest::index() const {
  // @@protoc_insertion_point(field_get:sts.AddCntRequest.index)
  return index_;
}
inline void AddCntRequest::set_index(::google::protobuf::int32 value) {
  
  index_ = value;
  // @@protoc_insertion_point(field_set:sts.AddCntRequest.index)
}

// -------------------------------------------------------------------

// ValueOfCnt

// int32 value = 1;
inline void ValueOfCnt::clear_value() {
  value_ = 0;
}
inline ::google::protobuf::int32 ValueOfCnt::value() const {
  // @@protoc_insertion_point(field_get:sts.ValueOfCnt.value)
  return value_;
}
inline void ValueOfCnt::set_value(::google::protobuf::int32 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:sts.ValueOfCnt.value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace sts

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_SeveralToSeveral_2eproto
