// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: one_to_one.proto
#ifndef GRPC_one_5fto_5fone_2eproto__INCLUDED
#define GRPC_one_5fto_5fone_2eproto__INCLUDED

#include "one_to_one.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace oto {

class one_to_one final {
 public:
  static constexpr char const* service_full_name() {
    return "oto.one_to_one";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Add_count(::grpc::ClientContext* context, const ::oto::addition& request, ::oto::count* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::oto::count>> AsyncAdd_count(::grpc::ClientContext* context, const ::oto::addition& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::oto::count>>(AsyncAdd_countRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::oto::count>> PrepareAsyncAdd_count(::grpc::ClientContext* context, const ::oto::addition& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::oto::count>>(PrepareAsyncAdd_countRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Add_count(::grpc::ClientContext* context, const ::oto::addition* request, ::oto::count* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Add_count(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::oto::count* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::oto::count>* AsyncAdd_countRaw(::grpc::ClientContext* context, const ::oto::addition& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::oto::count>* PrepareAsyncAdd_countRaw(::grpc::ClientContext* context, const ::oto::addition& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Add_count(::grpc::ClientContext* context, const ::oto::addition& request, ::oto::count* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::oto::count>> AsyncAdd_count(::grpc::ClientContext* context, const ::oto::addition& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::oto::count>>(AsyncAdd_countRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::oto::count>> PrepareAsyncAdd_count(::grpc::ClientContext* context, const ::oto::addition& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::oto::count>>(PrepareAsyncAdd_countRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Add_count(::grpc::ClientContext* context, const ::oto::addition* request, ::oto::count* response, std::function<void(::grpc::Status)>) override;
      void Add_count(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::oto::count* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::oto::count>* AsyncAdd_countRaw(::grpc::ClientContext* context, const ::oto::addition& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::oto::count>* PrepareAsyncAdd_countRaw(::grpc::ClientContext* context, const ::oto::addition& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Add_count_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Add_count(::grpc::ServerContext* context, const ::oto::addition* request, ::oto::count* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Add_count : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Add_count() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Add_count() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add_count(::grpc::ServerContext* context, const ::oto::addition* request, ::oto::count* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAdd_count(::grpc::ServerContext* context, ::oto::addition* request, ::grpc::ServerAsyncResponseWriter< ::oto::count>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Add_count<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Add_count : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_Add_count() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::oto::addition, ::oto::count>(
          [this](::grpc::ServerContext* context,
                 const ::oto::addition* request,
                 ::oto::count* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->Add_count(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_Add_count() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add_count(::grpc::ServerContext* context, const ::oto::addition* request, ::oto::count* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Add_count(::grpc::ServerContext* context, const ::oto::addition* request, ::oto::count* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_Add_count<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Add_count : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Add_count() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Add_count() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add_count(::grpc::ServerContext* context, const ::oto::addition* request, ::oto::count* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Add_count : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Add_count() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Add_count() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add_count(::grpc::ServerContext* context, const ::oto::addition* request, ::oto::count* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAdd_count(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Add_count : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_Add_count() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->Add_count(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_Add_count() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add_count(::grpc::ServerContext* context, const ::oto::addition* request, ::oto::count* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Add_count(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Add_count : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Add_count() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::oto::addition, ::oto::count>(std::bind(&WithStreamedUnaryMethod_Add_count<BaseClass>::StreamedAdd_count, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Add_count() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Add_count(::grpc::ServerContext* context, const ::oto::addition* request, ::oto::count* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAdd_count(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::oto::addition,::oto::count>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Add_count<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Add_count<Service > StreamedService;
};

}  // namespace oto


#endif  // GRPC_one_5fto_5fone_2eproto__INCLUDED
