// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: one_to_one.proto

#include "one_to_one.pb.h"
#include "one_to_one.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace oto {

static const char* one_to_one_method_names[] = {
  "/oto.one_to_one/Add_count",
};

std::unique_ptr< one_to_one::Stub> one_to_one::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< one_to_one::Stub> stub(new one_to_one::Stub(channel));
  return stub;
}

one_to_one::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Add_count_(one_to_one_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status one_to_one::Stub::Add_count(::grpc::ClientContext* context, const ::oto::addition& request, ::oto::count* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Add_count_, context, request, response);
}

void one_to_one::Stub::experimental_async::Add_count(::grpc::ClientContext* context, const ::oto::addition* request, ::oto::count* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Add_count_, context, request, response, std::move(f));
}

void one_to_one::Stub::experimental_async::Add_count(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::oto::count* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Add_count_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::oto::count>* one_to_one::Stub::AsyncAdd_countRaw(::grpc::ClientContext* context, const ::oto::addition& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::oto::count>::Create(channel_.get(), cq, rpcmethod_Add_count_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::oto::count>* one_to_one::Stub::PrepareAsyncAdd_countRaw(::grpc::ClientContext* context, const ::oto::addition& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::oto::count>::Create(channel_.get(), cq, rpcmethod_Add_count_, context, request, false);
}

one_to_one::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      one_to_one_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< one_to_one::Service, ::oto::addition, ::oto::count>(
          std::mem_fn(&one_to_one::Service::Add_count), this)));
}

one_to_one::Service::~Service() {
}

::grpc::Status one_to_one::Service::Add_count(::grpc::ServerContext* context, const ::oto::addition* request, ::oto::count* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace oto

